name: Dispatch analytics

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dispatch_token:
    if: github.repository == 'aws-powertools/powertools-lambda-python'
    runs-on: ubuntu-latest
    environment: layer-beta
    steps:
      # - name: Setup uptrem session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-actor: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.AWS_TEST }}

      - name: Print identity
        run: |
          aws sts get-caller-identity
