name: Dispatch analytics

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dispatch_token:
    if: github.repository == 'aws-powertools/powertools-lambda-python'
    runs-on: ubuntu-latest
    environment: layer-beta
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          role-to-assume: ${{ secrets.AWS_TEST }}

      - name: Print identity
        run: |
          aws sts get-caller-identity
